pipeline {
    agent {
      label 'slave2'
    }
    environment {
        DB_HOST = "13.233.91.52"
        DB_USER = "sharath"
        DB_PASS = "sharath"
    }
    stages {
        stage('Clone Repo') {
            steps {
               git branch: 'main', url: 'https://github.com/sharath0404/myapp.git'
            }
        }
        stage('Build App') {
            steps {
                echo "$PWD"
                sh "cd ${workspace}/myapp && mvn clean package"
            }
        }
        stage('Build Docker Image') {
             agent {
               label 'slave1'
             }
            steps {
                sh "cd ${workspace}/myapp docker build -t sharath441993/k8s:latest ."
        }
        }
        stage('Push to Docker Hub') {
            agent {
               label 'slave1'
             }
                stage('Push to Docker Hub') {
                    steps {
                        withDockerRegistry([credentialsId: 'docker-hub-credentials', url: 'https://index.docker.io/v1/']) {
                            sh 'docker push sharath441993/k8s:latest'
                            }
                    }
                }            

        }
}

        stage('Deploy to Kubernetes') {
            steps {
                sh "cd ${workspace}/myapp && kubectl apply -f k8s/deployment.yaml"
            }
        }
        stage('Test Database Connection') {
            steps {
                sh '''
                apt-get update && apt-get install -y mysql-client
                mysql -h $DB_HOST -u$DB_USER -p$DB_PASS -e "SHOW DATABASES;"
                '''
            }
        }
    }
}
